version: '3'

services:
  ton-mirror:
    build: ./
    restart: always
    ports:
      - "3000:3000"
    environment:
      CONFIG: '{"127.0.0.1:3000": { "domain": "https://example.com", "target": "https://example.com","secondary_domains": ["https://something.example.com"]}}'
    logging:
      options:
        max-size: 50m